import{a as u,s as f,i as d}from"./assets/vendor-da73009b.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))n(r);new MutationObserver(r=>{for(const o of r)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function a(r){const o={};return r.integrity&&(o.integrity=r.integrity),r.referrerPolicy&&(o.referrerPolicy=r.referrerPolicy),r.crossOrigin==="use-credentials"?o.credentials="include":r.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(r){if(r.ep)return;r.ep=!0;const o=a(r);fetch(r.href,o)}})();const y="44796717-c9697056d5a7f56baa85540ad",b="https://pixabay.com/api/";u.defaults.baseURL=b;function g({q:e="",page:s=1,per_page:a=15}={}){return u.get("",{params:{key:y,q:e,page:s,per_page:a,image_type:"photo",orientation:"horizontal",safesearch:!0}}).then(({data:n})=>n)}function h(e){return e.map(({webformatURL:s,largeImageURL:a,tags:n,likes:r,views:o,comments:c,downloads:p})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${a}">
            <img class="gallery-image" src="${s}" alt="${n}" width="360" height="152" />
            <ul class="description">
              <li class="description-items">
                <span class="item">Likes </span>${r}
              </li>
              <li class="description-items">
                <span class="item">Views </span>${o}
              </li>
              <li class="description-items">
                <span class="item">Comments </span>${c}
              </li>
              <li class="description-items">
                <span class="item">Downloads </span>${p}
              </li>
            </ul>
          </a>
        </li>`).join("")}const t={searchForm:document.querySelector(".search-form"),input:document.querySelector(".search-input"),gallery:document.querySelector(".card-container"),loader:document.querySelector(".loader"),loadMore:document.querySelector(".load-more"),btnLoad:document.querySelector(".btn")},i={q:"",page:1,per_page:15,maxPage:0},m=new f(".card-container a",{captionsData:"alt",captionDelay:250}),l={hide(e){e.classList.add("is-hidden")},show(e){e.classList.remove("is-hidden")},disable(e){e.disabled=!0},enable(e){e.disabled=!1}};t.searchForm.addEventListener("submit",L);t.btnLoad.addEventListener("click",w);async function L(e){e.preventDefault(),t.gallery.innerHTML="",l.hide(t.btnLoad),t.loader.classList.remove("visually-hidden"),i.page=1;const s=e.currentTarget;if(i.q=s.elements.query.value.trim(),!i.q){d.error({iconUrl:"./img/error.svg",message:"Search field cannot be empty!",position:"topRight",backgroundColor:"#ef4040",messageColor:"white",titleColor:"white"}),t.loader.classList.add("visually-hidden");return}try{const{totalHits:a,hits:n}=await g(i);i.maxPage=Math.ceil(a/i.per_page),t.gallery.innerHTML=h(n),n.length>0&&i.page<i.maxPage?l.show(t.btnLoad):(l.hide(t.btnLoad),d.info({iconUrl:"./img/info.svg",message:"We're sorry, but there are no more results.",position:"topRight",backgroundColor:"#09f",messageColor:"white",titleColor:"white"})),m.refresh()}catch(a){console.error(`Error during request: ${a}`),d.error({iconUrl:"./img/error.svg",message:`Error during request: ${a}`,position:"topRight",backgroundColor:"#ef4040",messageColor:"white",titleColor:"white"})}finally{s.reset(),t.loader.classList.add("visually-hidden")}}async function w(){l.hide(t.btnLoad),t.loadMore.classList.remove("visually-hidden"),i.page+=1;try{const{hits:e}=await g(i);t.gallery.insertAdjacentHTML("beforeend",h(e));const s=v();window.scrollBy({top:s*2,behavior:"smooth"}),i.page>=i.maxPage?(l.hide(t.btnLoad),d.info({iconUrl:"./img/info.svg",message:"We're sorry, but you've reached the end of search results.",position:"topRight",backgroundColor:"#09f",messageColor:"white",titleColor:"white"})):l.show(t.btnLoad),m.refresh()}catch(e){console.error(`Error during request: ${e}`),d.error({iconUrl:"./img/error.svg",message:`Error during request: ${e}`,position:"topRight",backgroundColor:"#ef4040",messageColor:"white",titleColor:"white"})}finally{l.enable(t.btnLoad),t.loadMore.classList.add("visually-hidden")}}function v(){const e=document.querySelector(".card-container .card");return e?e.getBoundingClientRect().height:0}
//# sourceMappingURL=commonHelpers.js.map
